KoiosBlogBackendBundle:
    resource: "@KoiosBlogBackendBundle/Resources/config/routing.yml"
    prefix:   /api/

KoiosBlogBundle:
    resource: "@KoiosBlogBundle/Resources/config/routing.yml"
    prefix:   /
