security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        main:
            entity: { class: Koios\BlogBundle\Entity\User, property: username }

    encoders:
        Koios\BlogBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
