parameters:
    koios_blog.emails.contact_email: contact@gmail.com
    koios_blog.comments.latest_comment_limit: 10

services:
    backend_client:
        class: Koios\BlogBundle\Services\BlogBackendClient
        arguments: ["%kernel.root_dir%/../src/Koios/BlogBundle/Resources/config/blog_api.json", "http://localhost:9900/app_dev.php/api"]