KoiosBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: KoiosBlogBundle:Page:index }
    requirements:
        _method:  GET

login:
    pattern: /login
    defaults: { _controller: KoiosBlogBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

KoiosBlogBundle_about:
    pattern: /about
    defaults: { _controller: KoiosBlogBundle:Page:about }
    requirements:
        _method: GET

KoiosBlogBundle_contact:
    pattern: /contact
    defaults: { _controller: KoiosBlogBundle:Page:contact }
    requirements:
        _method: GET|POST

KoiosBlogBundle_blog_show:
    pattern: /{id}/{slug}
    defaults: { _controller: KoiosBlogBundle:Blog:show }
    requirements:
        _method: GET
        id: \d+

KoiosBlogBundle_comment_create:
    pattern: /comment/{blog_id}
    defaults: { _controller: KoiosBlogBundle:Comment:create }
    requirements:
        _method: POST
        blog_id: \d+

KoiosBlogBundle_admin:
    pattern: /admin/
    defaults: { _controller: KoiosBlogBundle:Admin:index }
    requirements:
        _method: GET

KoiosBlogBundle_admin_blog_delete:
    pattern: /admin/delete/
    defaults: { _controller: KoiosBlogBundle:Admin:delete }
    requirements:
        _method: POST

KoiosBlogBundle_admin_blog_edit:
    pattern: /admin/edit/{id}
    defaults: { _controller: KoiosBlogBundle:Admin:edit }
    requirements:
        _method: GET|POST
        id: \d+

KoiosBlogBundle_admin_blog_create:
    pattern: /admin/create
    defaults: { _controller: KoiosBlogBundle:Admin:create }
    requirements:
        _method: GET|POST
